### PR TITLE
Fix CRC errors

### PR DESCRIPTION
**Pull request by danielcaceresm**
This pull request tries to improve the handling of decrypted messages and fix issues with crc.
Now the unknown bytes of a message are stored in the unknown property, and crc error must not be raised #7. I change the check to add log messages when unknown bytes exists.
Also, this PR fixed an issues parsing the log entries https://github.com/ronengr/hass_nuki_bt/issues/49, that prevents to configure the nuki 4 with the security pin.

I tested these changes locally, and they are working great with a Nuki 4.0 (non pro).

### CODE REVIEW

**Comment by ronengr** [comment]
Can you please explain the logic behind the fix a bit more?
Does this solve the issues with nuki 4?

I must say that i don't love the idea of having flexible message structures. the message structure is clearly defined in Nuki's specs (with exact padding and everything). so unless they changed the message length specifically for Nuki 4 (which is hard to imagine they did, as it breaks their own specs) I don't see a good reason to be so flexible with message structure.

We can add variable length message in cases we don't identify the message type, but i don't see a good reason to do it for messages we do identify correctly.

**Comment by ronengr** [comment]
OK, after re-reading all the commits, i agree with most of them except for the last one.
see comments in the commits.

**Comment by danielcaceresm** [comment]
@ronengr Thank you so much for reviewing the PR, and merge as fast as possible the changes you considered fine. About the changes in the log entries messages, I just tested your last version, and it throw and error parsing them.

The comment in my commit wasn't correct. I removed the padding because [reading the API doc](https://developer.nuki.io/page/nuki-smart-lock-api-2/2/#heading--log-entry), seems that the data field has different length for each type (the x = 1 for LogEntryExt1, x = 4 for LogEntryExt2, x = 5 for LogEntryExt3, and x = 1 for LogEntryExt4), and the padding tried to unify the message length. 

Removing the padding, I was able to pair a Nuki 4 setting the PIN without issues fixing https://github.com/ronengr/hass_nuki_bt/issues/49, and the next log entries are parsed correctly.

**Comment by ronengr** [comment]
@danielcaceresm 
Interesting. After reading the documentation again, you are of course correct.
For some reason in my nuki (nuki 3), i need the padding for it to work (otherwise I get a warning "Got unexpected message length for command LOG_ENTRY. Got 1 unknown bytes with value: b'\x00'")
It seems nuki3 doesn't follow the documentation and nuki 4 does :-)

I will make the padding optional to fix this.


Thanks again for the help

**Pull request closed without merging**
